/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Assembly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssemblyTests
    {
        // TODO uncomment below to declare an instance variable for Assembly
        //private Assembly instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Assembly
            //instance = new Assembly();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Assembly
        /// </summary>
        [Test]
        public void AssemblyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Assembly
            //Assert.IsInstanceOfType<Assembly> (instance, "variable 'instance' is a Assembly");
        }


        /// <summary>
        /// Test the property 'DefinedTypes'
        /// </summary>
        [Test]
        public void DefinedTypesTest()
        {
            // TODO unit test for the property 'DefinedTypes'
        }
        /// <summary>
        /// Test the property 'ExportedTypes'
        /// </summary>
        [Test]
        public void ExportedTypesTest()
        {
            // TODO unit test for the property 'ExportedTypes'
        }
        /// <summary>
        /// Test the property 'CodeBase'
        /// </summary>
        [Test]
        public void CodeBaseTest()
        {
            // TODO unit test for the property 'CodeBase'
        }
        /// <summary>
        /// Test the property 'EntryPoint'
        /// </summary>
        [Test]
        public void EntryPointTest()
        {
            // TODO unit test for the property 'EntryPoint'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'ImageRuntimeVersion'
        /// </summary>
        [Test]
        public void ImageRuntimeVersionTest()
        {
            // TODO unit test for the property 'ImageRuntimeVersion'
        }
        /// <summary>
        /// Test the property 'IsDynamic'
        /// </summary>
        [Test]
        public void IsDynamicTest()
        {
            // TODO unit test for the property 'IsDynamic'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'ReflectionOnly'
        /// </summary>
        [Test]
        public void ReflectionOnlyTest()
        {
            // TODO unit test for the property 'ReflectionOnly'
        }
        /// <summary>
        /// Test the property 'IsCollectible'
        /// </summary>
        [Test]
        public void IsCollectibleTest()
        {
            // TODO unit test for the property 'IsCollectible'
        }
        /// <summary>
        /// Test the property 'IsFullyTrusted'
        /// </summary>
        [Test]
        public void IsFullyTrustedTest()
        {
            // TODO unit test for the property 'IsFullyTrusted'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Test]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'EscapedCodeBase'
        /// </summary>
        [Test]
        public void EscapedCodeBaseTest()
        {
            // TODO unit test for the property 'EscapedCodeBase'
        }
        /// <summary>
        /// Test the property 'ManifestModule'
        /// </summary>
        [Test]
        public void ManifestModuleTest()
        {
            // TODO unit test for the property 'ManifestModule'
        }
        /// <summary>
        /// Test the property 'Modules'
        /// </summary>
        [Test]
        public void ModulesTest()
        {
            // TODO unit test for the property 'Modules'
        }
        /// <summary>
        /// Test the property 'GlobalAssemblyCache'
        /// </summary>
        [Test]
        public void GlobalAssemblyCacheTest()
        {
            // TODO unit test for the property 'GlobalAssemblyCache'
        }
        /// <summary>
        /// Test the property 'HostContext'
        /// </summary>
        [Test]
        public void HostContextTest()
        {
            // TODO unit test for the property 'HostContext'
        }
        /// <summary>
        /// Test the property 'SecurityRuleSet'
        /// </summary>
        [Test]
        public void SecurityRuleSetTest()
        {
            // TODO unit test for the property 'SecurityRuleSet'
        }

    }

}
