/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomAttributeTypedArgument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomAttributeTypedArgumentTests
    {
        // TODO uncomment below to declare an instance variable for CustomAttributeTypedArgument
        //private CustomAttributeTypedArgument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomAttributeTypedArgument
            //instance = new CustomAttributeTypedArgument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomAttributeTypedArgument
        /// </summary>
        [Test]
        public void CustomAttributeTypedArgumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomAttributeTypedArgument
            //Assert.IsInstanceOfType<CustomAttributeTypedArgument> (instance, "variable 'instance' is a CustomAttributeTypedArgument");
        }


        /// <summary>
        /// Test the property 'ArgumentType'
        /// </summary>
        [Test]
        public void ArgumentTypeTest()
        {
            // TODO unit test for the property 'ArgumentType'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
