/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomAttributeNamedArgument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomAttributeNamedArgumentTests
    {
        // TODO uncomment below to declare an instance variable for CustomAttributeNamedArgument
        //private CustomAttributeNamedArgument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomAttributeNamedArgument
            //instance = new CustomAttributeNamedArgument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomAttributeNamedArgument
        /// </summary>
        [Test]
        public void CustomAttributeNamedArgumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomAttributeNamedArgument
            //Assert.IsInstanceOfType<CustomAttributeNamedArgument> (instance, "variable 'instance' is a CustomAttributeNamedArgument");
        }


        /// <summary>
        /// Test the property 'MemberInfo'
        /// </summary>
        [Test]
        public void MemberInfoTest()
        {
            // TODO unit test for the property 'MemberInfo'
        }
        /// <summary>
        /// Test the property 'TypedValue'
        /// </summary>
        [Test]
        public void TypedValueTest()
        {
            // TODO unit test for the property 'TypedValue'
        }
        /// <summary>
        /// Test the property 'MemberName'
        /// </summary>
        [Test]
        public void MemberNameTest()
        {
            // TODO unit test for the property 'MemberName'
        }
        /// <summary>
        /// Test the property 'IsField'
        /// </summary>
        [Test]
        public void IsFieldTest()
        {
            // TODO unit test for the property 'IsField'
        }

    }

}
