/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomAttributeData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomAttributeDataTests
    {
        // TODO uncomment below to declare an instance variable for CustomAttributeData
        //private CustomAttributeData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomAttributeData
            //instance = new CustomAttributeData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomAttributeData
        /// </summary>
        [Test]
        public void CustomAttributeDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomAttributeData
            //Assert.IsInstanceOfType<CustomAttributeData> (instance, "variable 'instance' is a CustomAttributeData");
        }


        /// <summary>
        /// Test the property 'AttributeType'
        /// </summary>
        [Test]
        public void AttributeTypeTest()
        {
            // TODO unit test for the property 'AttributeType'
        }
        /// <summary>
        /// Test the property 'Constructor'
        /// </summary>
        [Test]
        public void ConstructorTest()
        {
            // TODO unit test for the property 'Constructor'
        }
        /// <summary>
        /// Test the property 'ConstructorArguments'
        /// </summary>
        [Test]
        public void ConstructorArgumentsTest()
        {
            // TODO unit test for the property 'ConstructorArguments'
        }
        /// <summary>
        /// Test the property 'NamedArguments'
        /// </summary>
        [Test]
        public void NamedArgumentsTest()
        {
            // TODO unit test for the property 'NamedArguments'
        }

    }

}
