/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EventInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EventInfoTests
    {
        // TODO uncomment below to declare an instance variable for EventInfo
        //private EventInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventInfo
            //instance = new EventInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventInfo
        /// </summary>
        [Test]
        public void EventInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventInfo
            //Assert.IsInstanceOfType<EventInfo> (instance, "variable 'instance' is a EventInfo");
        }


        /// <summary>
        /// Test the property 'MemberType'
        /// </summary>
        [Test]
        public void MemberTypeTest()
        {
            // TODO unit test for the property 'MemberType'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'IsSpecialName'
        /// </summary>
        [Test]
        public void IsSpecialNameTest()
        {
            // TODO unit test for the property 'IsSpecialName'
        }
        /// <summary>
        /// Test the property 'AddMethod'
        /// </summary>
        [Test]
        public void AddMethodTest()
        {
            // TODO unit test for the property 'AddMethod'
        }
        /// <summary>
        /// Test the property 'RemoveMethod'
        /// </summary>
        [Test]
        public void RemoveMethodTest()
        {
            // TODO unit test for the property 'RemoveMethod'
        }
        /// <summary>
        /// Test the property 'RaiseMethod'
        /// </summary>
        [Test]
        public void RaiseMethodTest()
        {
            // TODO unit test for the property 'RaiseMethod'
        }
        /// <summary>
        /// Test the property 'IsMulticast'
        /// </summary>
        [Test]
        public void IsMulticastTest()
        {
            // TODO unit test for the property 'IsMulticast'
        }
        /// <summary>
        /// Test the property 'EventHandlerType'
        /// </summary>
        [Test]
        public void EventHandlerTypeTest()
        {
            // TODO unit test for the property 'EventHandlerType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DeclaringType'
        /// </summary>
        [Test]
        public void DeclaringTypeTest()
        {
            // TODO unit test for the property 'DeclaringType'
        }
        /// <summary>
        /// Test the property 'ReflectedType'
        /// </summary>
        [Test]
        public void ReflectedTypeTest()
        {
            // TODO unit test for the property 'ReflectedType'
        }
        /// <summary>
        /// Test the property 'Module'
        /// </summary>
        [Test]
        public void ModuleTest()
        {
            // TODO unit test for the property 'Module'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Test]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'IsCollectible'
        /// </summary>
        [Test]
        public void IsCollectibleTest()
        {
            // TODO unit test for the property 'IsCollectible'
        }
        /// <summary>
        /// Test the property 'MetadataToken'
        /// </summary>
        [Test]
        public void MetadataTokenTest()
        {
            // TODO unit test for the property 'MetadataToken'
        }

    }

}
