/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Exception
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExceptionTests
    {
        // TODO uncomment below to declare an instance variable for Exception
        //private Exception instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Exception
            //instance = new Exception();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Exception
        /// </summary>
        [Test]
        public void ExceptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Exception
            //Assert.IsInstanceOfType<Exception> (instance, "variable 'instance' is a Exception");
        }


        /// <summary>
        /// Test the property 'TargetSite'
        /// </summary>
        [Test]
        public void TargetSiteTest()
        {
            // TODO unit test for the property 'TargetSite'
        }
        /// <summary>
        /// Test the property 'StackTrace'
        /// </summary>
        [Test]
        public void StackTraceTest()
        {
            // TODO unit test for the property 'StackTrace'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'InnerException'
        /// </summary>
        [Test]
        public void InnerExceptionTest()
        {
            // TODO unit test for the property 'InnerException'
        }
        /// <summary>
        /// Test the property 'HelpLink'
        /// </summary>
        [Test]
        public void HelpLinkTest()
        {
            // TODO unit test for the property 'HelpLink'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'HResult'
        /// </summary>
        [Test]
        public void HResultTest()
        {
            // TODO unit test for the property 'HResult'
        }

    }

}
