/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelStateEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelStateEntryTests
    {
        // TODO uncomment below to declare an instance variable for ModelStateEntry
        //private ModelStateEntry instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelStateEntry
            //instance = new ModelStateEntry();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelStateEntry
        /// </summary>
        [Test]
        public void ModelStateEntryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelStateEntry
            //Assert.IsInstanceOfType<ModelStateEntry> (instance, "variable 'instance' is a ModelStateEntry");
        }


        /// <summary>
        /// Test the property 'RawValue'
        /// </summary>
        [Test]
        public void RawValueTest()
        {
            // TODO unit test for the property 'RawValue'
        }
        /// <summary>
        /// Test the property 'AttemptedValue'
        /// </summary>
        [Test]
        public void AttemptedValueTest()
        {
            // TODO unit test for the property 'AttemptedValue'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'ValidationState'
        /// </summary>
        [Test]
        public void ValidationStateTest()
        {
            // TODO unit test for the property 'ValidationState'
        }
        /// <summary>
        /// Test the property 'IsContainerNode'
        /// </summary>
        [Test]
        public void IsContainerNodeTest()
        {
            // TODO unit test for the property 'IsContainerNode'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Test]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

    }

}
