/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModuleHandle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModuleHandleTests
    {
        // TODO uncomment below to declare an instance variable for ModuleHandle
        //private ModuleHandle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModuleHandle
            //instance = new ModuleHandle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModuleHandle
        /// </summary>
        [Test]
        public void ModuleHandleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModuleHandle
            //Assert.IsInstanceOfType<ModuleHandle> (instance, "variable 'instance' is a ModuleHandle");
        }


        /// <summary>
        /// Test the property 'MdStreamVersion'
        /// </summary>
        [Test]
        public void MdStreamVersionTest()
        {
            // TODO unit test for the property 'MdStreamVersion'
        }

    }

}
