/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Module
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModuleTests
    {
        // TODO uncomment below to declare an instance variable for Module
        //private Module instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Module
            //instance = new Module();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Module
        /// </summary>
        [Test]
        public void ModuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Module
            //Assert.IsInstanceOfType<Module> (instance, "variable 'instance' is a Module");
        }


        /// <summary>
        /// Test the property 'Assembly'
        /// </summary>
        [Test]
        public void AssemblyTest()
        {
            // TODO unit test for the property 'Assembly'
        }
        /// <summary>
        /// Test the property 'FullyQualifiedName'
        /// </summary>
        [Test]
        public void FullyQualifiedNameTest()
        {
            // TODO unit test for the property 'FullyQualifiedName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MdStreamVersion'
        /// </summary>
        [Test]
        public void MdStreamVersionTest()
        {
            // TODO unit test for the property 'MdStreamVersion'
        }
        /// <summary>
        /// Test the property 'ModuleVersionId'
        /// </summary>
        [Test]
        public void ModuleVersionIdTest()
        {
            // TODO unit test for the property 'ModuleVersionId'
        }
        /// <summary>
        /// Test the property 'ScopeName'
        /// </summary>
        [Test]
        public void ScopeNameTest()
        {
            // TODO unit test for the property 'ScopeName'
        }
        /// <summary>
        /// Test the property 'ModuleHandle'
        /// </summary>
        [Test]
        public void ModuleHandleTest()
        {
            // TODO unit test for the property 'ModuleHandle'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Test]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'MetadataToken'
        /// </summary>
        [Test]
        public void MetadataTokenTest()
        {
            // TODO unit test for the property 'MetadataToken'
        }

    }

}
