/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ParameterInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ParameterInfoTests
    {
        // TODO uncomment below to declare an instance variable for ParameterInfo
        //private ParameterInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParameterInfo
            //instance = new ParameterInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParameterInfo
        /// </summary>
        [Test]
        public void ParameterInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ParameterInfo
            //Assert.IsInstanceOfType<ParameterInfo> (instance, "variable 'instance' is a ParameterInfo");
        }


        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Test]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParameterType'
        /// </summary>
        [Test]
        public void ParameterTypeTest()
        {
            // TODO unit test for the property 'ParameterType'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'IsIn'
        /// </summary>
        [Test]
        public void IsInTest()
        {
            // TODO unit test for the property 'IsIn'
        }
        /// <summary>
        /// Test the property 'IsLcid'
        /// </summary>
        [Test]
        public void IsLcidTest()
        {
            // TODO unit test for the property 'IsLcid'
        }
        /// <summary>
        /// Test the property 'IsOptional'
        /// </summary>
        [Test]
        public void IsOptionalTest()
        {
            // TODO unit test for the property 'IsOptional'
        }
        /// <summary>
        /// Test the property 'IsOut'
        /// </summary>
        [Test]
        public void IsOutTest()
        {
            // TODO unit test for the property 'IsOut'
        }
        /// <summary>
        /// Test the property 'IsRetval'
        /// </summary>
        [Test]
        public void IsRetvalTest()
        {
            // TODO unit test for the property 'IsRetval'
        }
        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Test]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }
        /// <summary>
        /// Test the property 'RawDefaultValue'
        /// </summary>
        [Test]
        public void RawDefaultValueTest()
        {
            // TODO unit test for the property 'RawDefaultValue'
        }
        /// <summary>
        /// Test the property 'HasDefaultValue'
        /// </summary>
        [Test]
        public void HasDefaultValueTest()
        {
            // TODO unit test for the property 'HasDefaultValue'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Test]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'MetadataToken'
        /// </summary>
        [Test]
        public void MetadataTokenTest()
        {
            // TODO unit test for the property 'MetadataToken'
        }

    }

}
