/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PropertyInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PropertyInfoTests
    {
        // TODO uncomment below to declare an instance variable for PropertyInfo
        //private PropertyInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertyInfo
            //instance = new PropertyInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertyInfo
        /// </summary>
        [Test]
        public void PropertyInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PropertyInfo
            //Assert.IsInstanceOfType<PropertyInfo> (instance, "variable 'instance' is a PropertyInfo");
        }


        /// <summary>
        /// Test the property 'MemberType'
        /// </summary>
        [Test]
        public void MemberTypeTest()
        {
            // TODO unit test for the property 'MemberType'
        }
        /// <summary>
        /// Test the property 'PropertyType'
        /// </summary>
        [Test]
        public void PropertyTypeTest()
        {
            // TODO unit test for the property 'PropertyType'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'IsSpecialName'
        /// </summary>
        [Test]
        public void IsSpecialNameTest()
        {
            // TODO unit test for the property 'IsSpecialName'
        }
        /// <summary>
        /// Test the property 'CanRead'
        /// </summary>
        [Test]
        public void CanReadTest()
        {
            // TODO unit test for the property 'CanRead'
        }
        /// <summary>
        /// Test the property 'CanWrite'
        /// </summary>
        [Test]
        public void CanWriteTest()
        {
            // TODO unit test for the property 'CanWrite'
        }
        /// <summary>
        /// Test the property 'GetMethod'
        /// </summary>
        [Test]
        public void GetMethodTest()
        {
            // TODO unit test for the property 'GetMethod'
        }
        /// <summary>
        /// Test the property 'SetMethod'
        /// </summary>
        [Test]
        public void SetMethodTest()
        {
            // TODO unit test for the property 'SetMethod'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DeclaringType'
        /// </summary>
        [Test]
        public void DeclaringTypeTest()
        {
            // TODO unit test for the property 'DeclaringType'
        }
        /// <summary>
        /// Test the property 'ReflectedType'
        /// </summary>
        [Test]
        public void ReflectedTypeTest()
        {
            // TODO unit test for the property 'ReflectedType'
        }
        /// <summary>
        /// Test the property 'Module'
        /// </summary>
        [Test]
        public void ModuleTest()
        {
            // TODO unit test for the property 'Module'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Test]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'IsCollectible'
        /// </summary>
        [Test]
        public void IsCollectibleTest()
        {
            // TODO unit test for the property 'IsCollectible'
        }
        /// <summary>
        /// Test the property 'MetadataToken'
        /// </summary>
        [Test]
        public void MetadataTokenTest()
        {
            // TODO unit test for the property 'MetadataToken'
        }

    }

}
