/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines EventAttributes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum EventAttributes
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 1,
        /// <summary>
        /// Enum NUMBER_512 for value: 512
        /// </summary>
        [EnumMember(Value = "512")]
        NUMBER_512 = 2,
        /// <summary>
        /// Enum NUMBER_1024 for value: 1024
        /// </summary>
        [EnumMember(Value = "1024")]
        NUMBER_1024 = 3,
        /// <summary>
        /// Enum NUMBER_1024 for value: 1024
        /// </summary>
        [EnumMember(Value = "1024")]
        NUMBER_1024 = 4    }
}
