/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FieldInfo
    /// </summary>
    [DataContract]
        public partial class FieldInfo :  IEquatable<FieldInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldInfo" /> class.
        /// </summary>
        public FieldInfo()
        {
        }
        
        /// <summary>
        /// Gets or Sets MemberType
        /// </summary>
        [DataMember(Name="memberType", EmitDefaultValue=false)]
        public  MemberType { get; private set; }

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public  Attributes { get; private set; }

        /// <summary>
        /// Gets or Sets FieldType
        /// </summary>
        [DataMember(Name="fieldType", EmitDefaultValue=false)]
        public  FieldType { get; private set; }

        /// <summary>
        /// Gets or Sets IsInitOnly
        /// </summary>
        [DataMember(Name="isInitOnly", EmitDefaultValue=false)]
        public bool? IsInitOnly { get; private set; }

        /// <summary>
        /// Gets or Sets IsLiteral
        /// </summary>
        [DataMember(Name="isLiteral", EmitDefaultValue=false)]
        public bool? IsLiteral { get; private set; }

        /// <summary>
        /// Gets or Sets IsNotSerialized
        /// </summary>
        [DataMember(Name="isNotSerialized", EmitDefaultValue=false)]
        public bool? IsNotSerialized { get; private set; }

        /// <summary>
        /// Gets or Sets IsPinvokeImpl
        /// </summary>
        [DataMember(Name="isPinvokeImpl", EmitDefaultValue=false)]
        public bool? IsPinvokeImpl { get; private set; }

        /// <summary>
        /// Gets or Sets IsSpecialName
        /// </summary>
        [DataMember(Name="isSpecialName", EmitDefaultValue=false)]
        public bool? IsSpecialName { get; private set; }

        /// <summary>
        /// Gets or Sets IsStatic
        /// </summary>
        [DataMember(Name="isStatic", EmitDefaultValue=false)]
        public bool? IsStatic { get; private set; }

        /// <summary>
        /// Gets or Sets IsAssembly
        /// </summary>
        [DataMember(Name="isAssembly", EmitDefaultValue=false)]
        public bool? IsAssembly { get; private set; }

        /// <summary>
        /// Gets or Sets IsFamily
        /// </summary>
        [DataMember(Name="isFamily", EmitDefaultValue=false)]
        public bool? IsFamily { get; private set; }

        /// <summary>
        /// Gets or Sets IsFamilyAndAssembly
        /// </summary>
        [DataMember(Name="isFamilyAndAssembly", EmitDefaultValue=false)]
        public bool? IsFamilyAndAssembly { get; private set; }

        /// <summary>
        /// Gets or Sets IsFamilyOrAssembly
        /// </summary>
        [DataMember(Name="isFamilyOrAssembly", EmitDefaultValue=false)]
        public bool? IsFamilyOrAssembly { get; private set; }

        /// <summary>
        /// Gets or Sets IsPrivate
        /// </summary>
        [DataMember(Name="isPrivate", EmitDefaultValue=false)]
        public bool? IsPrivate { get; private set; }

        /// <summary>
        /// Gets or Sets IsPublic
        /// </summary>
        [DataMember(Name="isPublic", EmitDefaultValue=false)]
        public bool? IsPublic { get; private set; }

        /// <summary>
        /// Gets or Sets IsSecurityCritical
        /// </summary>
        [DataMember(Name="isSecurityCritical", EmitDefaultValue=false)]
        public bool? IsSecurityCritical { get; private set; }

        /// <summary>
        /// Gets or Sets IsSecuritySafeCritical
        /// </summary>
        [DataMember(Name="isSecuritySafeCritical", EmitDefaultValue=false)]
        public bool? IsSecuritySafeCritical { get; private set; }

        /// <summary>
        /// Gets or Sets IsSecurityTransparent
        /// </summary>
        [DataMember(Name="isSecurityTransparent", EmitDefaultValue=false)]
        public bool? IsSecurityTransparent { get; private set; }

        /// <summary>
        /// Gets or Sets FieldHandle
        /// </summary>
        [DataMember(Name="fieldHandle", EmitDefaultValue=false)]
        public  FieldHandle { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; private set; }

        /// <summary>
        /// Gets or Sets DeclaringType
        /// </summary>
        [DataMember(Name="declaringType", EmitDefaultValue=false)]
        public  DeclaringType { get; private set; }

        /// <summary>
        /// Gets or Sets ReflectedType
        /// </summary>
        [DataMember(Name="reflectedType", EmitDefaultValue=false)]
        public  ReflectedType { get; private set; }

        /// <summary>
        /// Gets or Sets Module
        /// </summary>
        [DataMember(Name="module", EmitDefaultValue=false)]
        public  Module { get; private set; }

        /// <summary>
        /// Gets or Sets CustomAttributes
        /// </summary>
        [DataMember(Name="customAttributes", EmitDefaultValue=false)]
        public List<CustomAttributeData> CustomAttributes { get; private set; }

        /// <summary>
        /// Gets or Sets IsCollectible
        /// </summary>
        [DataMember(Name="isCollectible", EmitDefaultValue=false)]
        public bool? IsCollectible { get; private set; }

        /// <summary>
        /// Gets or Sets MetadataToken
        /// </summary>
        [DataMember(Name="metadataToken", EmitDefaultValue=false)]
        public int? MetadataToken { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FieldInfo {\n");
            sb.Append("  MemberType: ").Append(MemberType).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  FieldType: ").Append(FieldType).Append("\n");
            sb.Append("  IsInitOnly: ").Append(IsInitOnly).Append("\n");
            sb.Append("  IsLiteral: ").Append(IsLiteral).Append("\n");
            sb.Append("  IsNotSerialized: ").Append(IsNotSerialized).Append("\n");
            sb.Append("  IsPinvokeImpl: ").Append(IsPinvokeImpl).Append("\n");
            sb.Append("  IsSpecialName: ").Append(IsSpecialName).Append("\n");
            sb.Append("  IsStatic: ").Append(IsStatic).Append("\n");
            sb.Append("  IsAssembly: ").Append(IsAssembly).Append("\n");
            sb.Append("  IsFamily: ").Append(IsFamily).Append("\n");
            sb.Append("  IsFamilyAndAssembly: ").Append(IsFamilyAndAssembly).Append("\n");
            sb.Append("  IsFamilyOrAssembly: ").Append(IsFamilyOrAssembly).Append("\n");
            sb.Append("  IsPrivate: ").Append(IsPrivate).Append("\n");
            sb.Append("  IsPublic: ").Append(IsPublic).Append("\n");
            sb.Append("  IsSecurityCritical: ").Append(IsSecurityCritical).Append("\n");
            sb.Append("  IsSecuritySafeCritical: ").Append(IsSecuritySafeCritical).Append("\n");
            sb.Append("  IsSecurityTransparent: ").Append(IsSecurityTransparent).Append("\n");
            sb.Append("  FieldHandle: ").Append(FieldHandle).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DeclaringType: ").Append(DeclaringType).Append("\n");
            sb.Append("  ReflectedType: ").Append(ReflectedType).Append("\n");
            sb.Append("  Module: ").Append(Module).Append("\n");
            sb.Append("  CustomAttributes: ").Append(CustomAttributes).Append("\n");
            sb.Append("  IsCollectible: ").Append(IsCollectible).Append("\n");
            sb.Append("  MetadataToken: ").Append(MetadataToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FieldInfo);
        }

        /// <summary>
        /// Returns true if FieldInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of FieldInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FieldInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MemberType == input.MemberType ||
                    this.MemberType != null &&
                    input.MemberType != null &&
                    this.MemberType.SequenceEqual(input.MemberType)
                ) && 
                (
                    this.Attributes == input.Attributes ||
                    this.Attributes != null &&
                    input.Attributes != null &&
                    this.Attributes.SequenceEqual(input.Attributes)
                ) && 
                (
                    this.FieldType == input.FieldType ||
                    this.FieldType != null &&
                    input.FieldType != null &&
                    this.FieldType.SequenceEqual(input.FieldType)
                ) && 
                (
                    this.IsInitOnly == input.IsInitOnly ||
                    (this.IsInitOnly != null &&
                    this.IsInitOnly.Equals(input.IsInitOnly))
                ) && 
                (
                    this.IsLiteral == input.IsLiteral ||
                    (this.IsLiteral != null &&
                    this.IsLiteral.Equals(input.IsLiteral))
                ) && 
                (
                    this.IsNotSerialized == input.IsNotSerialized ||
                    (this.IsNotSerialized != null &&
                    this.IsNotSerialized.Equals(input.IsNotSerialized))
                ) && 
                (
                    this.IsPinvokeImpl == input.IsPinvokeImpl ||
                    (this.IsPinvokeImpl != null &&
                    this.IsPinvokeImpl.Equals(input.IsPinvokeImpl))
                ) && 
                (
                    this.IsSpecialName == input.IsSpecialName ||
                    (this.IsSpecialName != null &&
                    this.IsSpecialName.Equals(input.IsSpecialName))
                ) && 
                (
                    this.IsStatic == input.IsStatic ||
                    (this.IsStatic != null &&
                    this.IsStatic.Equals(input.IsStatic))
                ) && 
                (
                    this.IsAssembly == input.IsAssembly ||
                    (this.IsAssembly != null &&
                    this.IsAssembly.Equals(input.IsAssembly))
                ) && 
                (
                    this.IsFamily == input.IsFamily ||
                    (this.IsFamily != null &&
                    this.IsFamily.Equals(input.IsFamily))
                ) && 
                (
                    this.IsFamilyAndAssembly == input.IsFamilyAndAssembly ||
                    (this.IsFamilyAndAssembly != null &&
                    this.IsFamilyAndAssembly.Equals(input.IsFamilyAndAssembly))
                ) && 
                (
                    this.IsFamilyOrAssembly == input.IsFamilyOrAssembly ||
                    (this.IsFamilyOrAssembly != null &&
                    this.IsFamilyOrAssembly.Equals(input.IsFamilyOrAssembly))
                ) && 
                (
                    this.IsPrivate == input.IsPrivate ||
                    (this.IsPrivate != null &&
                    this.IsPrivate.Equals(input.IsPrivate))
                ) && 
                (
                    this.IsPublic == input.IsPublic ||
                    (this.IsPublic != null &&
                    this.IsPublic.Equals(input.IsPublic))
                ) && 
                (
                    this.IsSecurityCritical == input.IsSecurityCritical ||
                    (this.IsSecurityCritical != null &&
                    this.IsSecurityCritical.Equals(input.IsSecurityCritical))
                ) && 
                (
                    this.IsSecuritySafeCritical == input.IsSecuritySafeCritical ||
                    (this.IsSecuritySafeCritical != null &&
                    this.IsSecuritySafeCritical.Equals(input.IsSecuritySafeCritical))
                ) && 
                (
                    this.IsSecurityTransparent == input.IsSecurityTransparent ||
                    (this.IsSecurityTransparent != null &&
                    this.IsSecurityTransparent.Equals(input.IsSecurityTransparent))
                ) && 
                (
                    this.FieldHandle == input.FieldHandle ||
                    this.FieldHandle != null &&
                    input.FieldHandle != null &&
                    this.FieldHandle.SequenceEqual(input.FieldHandle)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.DeclaringType == input.DeclaringType ||
                    this.DeclaringType != null &&
                    input.DeclaringType != null &&
                    this.DeclaringType.SequenceEqual(input.DeclaringType)
                ) && 
                (
                    this.ReflectedType == input.ReflectedType ||
                    this.ReflectedType != null &&
                    input.ReflectedType != null &&
                    this.ReflectedType.SequenceEqual(input.ReflectedType)
                ) && 
                (
                    this.Module == input.Module ||
                    this.Module != null &&
                    input.Module != null &&
                    this.Module.SequenceEqual(input.Module)
                ) && 
                (
                    this.CustomAttributes == input.CustomAttributes ||
                    this.CustomAttributes != null &&
                    input.CustomAttributes != null &&
                    this.CustomAttributes.SequenceEqual(input.CustomAttributes)
                ) && 
                (
                    this.IsCollectible == input.IsCollectible ||
                    (this.IsCollectible != null &&
                    this.IsCollectible.Equals(input.IsCollectible))
                ) && 
                (
                    this.MetadataToken == input.MetadataToken ||
                    (this.MetadataToken != null &&
                    this.MetadataToken.Equals(input.MetadataToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MemberType != null)
                    hashCode = hashCode * 59 + this.MemberType.GetHashCode();
                if (this.Attributes != null)
                    hashCode = hashCode * 59 + this.Attributes.GetHashCode();
                if (this.FieldType != null)
                    hashCode = hashCode * 59 + this.FieldType.GetHashCode();
                if (this.IsInitOnly != null)
                    hashCode = hashCode * 59 + this.IsInitOnly.GetHashCode();
                if (this.IsLiteral != null)
                    hashCode = hashCode * 59 + this.IsLiteral.GetHashCode();
                if (this.IsNotSerialized != null)
                    hashCode = hashCode * 59 + this.IsNotSerialized.GetHashCode();
                if (this.IsPinvokeImpl != null)
                    hashCode = hashCode * 59 + this.IsPinvokeImpl.GetHashCode();
                if (this.IsSpecialName != null)
                    hashCode = hashCode * 59 + this.IsSpecialName.GetHashCode();
                if (this.IsStatic != null)
                    hashCode = hashCode * 59 + this.IsStatic.GetHashCode();
                if (this.IsAssembly != null)
                    hashCode = hashCode * 59 + this.IsAssembly.GetHashCode();
                if (this.IsFamily != null)
                    hashCode = hashCode * 59 + this.IsFamily.GetHashCode();
                if (this.IsFamilyAndAssembly != null)
                    hashCode = hashCode * 59 + this.IsFamilyAndAssembly.GetHashCode();
                if (this.IsFamilyOrAssembly != null)
                    hashCode = hashCode * 59 + this.IsFamilyOrAssembly.GetHashCode();
                if (this.IsPrivate != null)
                    hashCode = hashCode * 59 + this.IsPrivate.GetHashCode();
                if (this.IsPublic != null)
                    hashCode = hashCode * 59 + this.IsPublic.GetHashCode();
                if (this.IsSecurityCritical != null)
                    hashCode = hashCode * 59 + this.IsSecurityCritical.GetHashCode();
                if (this.IsSecuritySafeCritical != null)
                    hashCode = hashCode * 59 + this.IsSecuritySafeCritical.GetHashCode();
                if (this.IsSecurityTransparent != null)
                    hashCode = hashCode * 59 + this.IsSecurityTransparent.GetHashCode();
                if (this.FieldHandle != null)
                    hashCode = hashCode * 59 + this.FieldHandle.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.DeclaringType != null)
                    hashCode = hashCode * 59 + this.DeclaringType.GetHashCode();
                if (this.ReflectedType != null)
                    hashCode = hashCode * 59 + this.ReflectedType.GetHashCode();
                if (this.Module != null)
                    hashCode = hashCode * 59 + this.Module.GetHashCode();
                if (this.CustomAttributes != null)
                    hashCode = hashCode * 59 + this.CustomAttributes.GetHashCode();
                if (this.IsCollectible != null)
                    hashCode = hashCode * 59 + this.IsCollectible.GetHashCode();
                if (this.MetadataToken != null)
                    hashCode = hashCode * 59 + this.MetadataToken.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
