/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ParameterAttributes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ParameterAttributes
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 1,
        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        NUMBER_1 = 2,
        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        NUMBER_2 = 3,
        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        NUMBER_4 = 4,
        /// <summary>
        /// Enum NUMBER_8 for value: 8
        /// </summary>
        [EnumMember(Value = "8")]
        NUMBER_8 = 5,
        /// <summary>
        /// Enum NUMBER_16 for value: 16
        /// </summary>
        [EnumMember(Value = "16")]
        NUMBER_16 = 6,
        /// <summary>
        /// Enum NUMBER_4096 for value: 4096
        /// </summary>
        [EnumMember(Value = "4096")]
        NUMBER_4096 = 7,
        /// <summary>
        /// Enum NUMBER_8192 for value: 8192
        /// </summary>
        [EnumMember(Value = "8192")]
        NUMBER_8192 = 8,
        /// <summary>
        /// Enum NUMBER_16384 for value: 16384
        /// </summary>
        [EnumMember(Value = "16384")]
        NUMBER_16384 = 9,
        /// <summary>
        /// Enum NUMBER_32768 for value: 32768
        /// </summary>
        [EnumMember(Value = "32768")]
        NUMBER_32768 = 10,
        /// <summary>
        /// Enum NUMBER_61440 for value: 61440
        /// </summary>
        [EnumMember(Value = "61440")]
        NUMBER_61440 = 11    }
}
