/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines PropertyAttributes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum PropertyAttributes
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 1,
        /// <summary>
        /// Enum NUMBER_512 for value: 512
        /// </summary>
        [EnumMember(Value = "512")]
        NUMBER_512 = 2,
        /// <summary>
        /// Enum NUMBER_1024 for value: 1024
        /// </summary>
        [EnumMember(Value = "1024")]
        NUMBER_1024 = 3,
        /// <summary>
        /// Enum NUMBER_4096 for value: 4096
        /// </summary>
        [EnumMember(Value = "4096")]
        NUMBER_4096 = 4,
        /// <summary>
        /// Enum NUMBER_8192 for value: 8192
        /// </summary>
        [EnumMember(Value = "8192")]
        NUMBER_8192 = 5,
        /// <summary>
        /// Enum NUMBER_16384 for value: 16384
        /// </summary>
        [EnumMember(Value = "16384")]
        NUMBER_16384 = 6,
        /// <summary>
        /// Enum NUMBER_32768 for value: 32768
        /// </summary>
        [EnumMember(Value = "32768")]
        NUMBER_32768 = 7,
        /// <summary>
        /// Enum NUMBER_62464 for value: 62464
        /// </summary>
        [EnumMember(Value = "62464")]
        NUMBER_62464 = 8    }
}
