/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines TypeAttributes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeAttributes
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 1,
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 2,
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 3,
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 4,
        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        NUMBER_1 = 5,
        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        NUMBER_2 = 6,
        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        [EnumMember(Value = "3")]
        NUMBER_3 = 7,
        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        NUMBER_4 = 8,
        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        [EnumMember(Value = "5")]
        NUMBER_5 = 9,
        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        [EnumMember(Value = "6")]
        NUMBER_6 = 10,
        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        [EnumMember(Value = "7")]
        NUMBER_7 = 11,
        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        [EnumMember(Value = "7")]
        NUMBER_7 = 12,
        /// <summary>
        /// Enum NUMBER_8 for value: 8
        /// </summary>
        [EnumMember(Value = "8")]
        NUMBER_8 = 13,
        /// <summary>
        /// Enum NUMBER_16 for value: 16
        /// </summary>
        [EnumMember(Value = "16")]
        NUMBER_16 = 14,
        /// <summary>
        /// Enum NUMBER_24 for value: 24
        /// </summary>
        [EnumMember(Value = "24")]
        NUMBER_24 = 15,
        /// <summary>
        /// Enum NUMBER_32 for value: 32
        /// </summary>
        [EnumMember(Value = "32")]
        NUMBER_32 = 16,
        /// <summary>
        /// Enum NUMBER_32 for value: 32
        /// </summary>
        [EnumMember(Value = "32")]
        NUMBER_32 = 17,
        /// <summary>
        /// Enum NUMBER_128 for value: 128
        /// </summary>
        [EnumMember(Value = "128")]
        NUMBER_128 = 18,
        /// <summary>
        /// Enum NUMBER_256 for value: 256
        /// </summary>
        [EnumMember(Value = "256")]
        NUMBER_256 = 19,
        /// <summary>
        /// Enum NUMBER_1024 for value: 1024
        /// </summary>
        [EnumMember(Value = "1024")]
        NUMBER_1024 = 20,
        /// <summary>
        /// Enum NUMBER_2048 for value: 2048
        /// </summary>
        [EnumMember(Value = "2048")]
        NUMBER_2048 = 21,
        /// <summary>
        /// Enum NUMBER_4096 for value: 4096
        /// </summary>
        [EnumMember(Value = "4096")]
        NUMBER_4096 = 22,
        /// <summary>
        /// Enum NUMBER_8192 for value: 8192
        /// </summary>
        [EnumMember(Value = "8192")]
        NUMBER_8192 = 23,
        /// <summary>
        /// Enum NUMBER_16384 for value: 16384
        /// </summary>
        [EnumMember(Value = "16384")]
        NUMBER_16384 = 24,
        /// <summary>
        /// Enum NUMBER_65536 for value: 65536
        /// </summary>
        [EnumMember(Value = "65536")]
        NUMBER_65536 = 25,
        /// <summary>
        /// Enum NUMBER_131072 for value: 131072
        /// </summary>
        [EnumMember(Value = "131072")]
        NUMBER_131072 = 26,
        /// <summary>
        /// Enum NUMBER_196608 for value: 196608
        /// </summary>
        [EnumMember(Value = "196608")]
        NUMBER_196608 = 27,
        /// <summary>
        /// Enum NUMBER_196608 for value: 196608
        /// </summary>
        [EnumMember(Value = "196608")]
        NUMBER_196608 = 28,
        /// <summary>
        /// Enum NUMBER_262144 for value: 262144
        /// </summary>
        [EnumMember(Value = "262144")]
        NUMBER_262144 = 29,
        /// <summary>
        /// Enum NUMBER_264192 for value: 264192
        /// </summary>
        [EnumMember(Value = "264192")]
        NUMBER_264192 = 30,
        /// <summary>
        /// Enum NUMBER_1048576 for value: 1048576
        /// </summary>
        [EnumMember(Value = "1048576")]
        NUMBER_1048576 = 31,
        /// <summary>
        /// Enum NUMBER_12582912 for value: 12582912
        /// </summary>
        [EnumMember(Value = "12582912")]
        NUMBER_12582912 = 32    }
}
