/* 
 * Library API
 *
 * Through this API you can access authors and their books
 *
 * OpenAPI spec version: 1.0
 * Contact: bailleul.sacha@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AuthorsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AuthorsApiTests
    {
        private AuthorsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AuthorsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuthorsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AuthorsApi
            //Assert.IsInstanceOfType(typeof(AuthorsApi), instance, "instance is a AuthorsApi");
        }

        /// <summary>
        /// Test ApiVversionAuthorsAuthorIdGet
        /// </summary>
        [Test]
        public void ApiVversionAuthorsAuthorIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? authorId = null;
            //string version = null;
            //var response = instance.ApiVversionAuthorsAuthorIdGet(authorId, version);
            //Assert.IsInstanceOf<Author> (response, "response is Author");
        }
        /// <summary>
        /// Test ApiVversionAuthorsAuthorIdPatch
        /// </summary>
        [Test]
        public void ApiVversionAuthorsAuthorIdPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? authorId = null;
            //string version = null;
            //List<Operation> body = null;
            //var response = instance.ApiVversionAuthorsAuthorIdPatch(authorId, version, body);
            //Assert.IsInstanceOf<Author> (response, "response is Author");
        }
        /// <summary>
        /// Test ApiVversionAuthorsAuthorIdPut
        /// </summary>
        [Test]
        public void ApiVversionAuthorsAuthorIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? authorId = null;
            //string version = null;
            //AuthorForUpdate body = null;
            //var response = instance.ApiVversionAuthorsAuthorIdPut(authorId, version, body);
            //Assert.IsInstanceOf<Author> (response, "response is Author");
        }
        /// <summary>
        /// Test ApiVversionAuthorsGet
        /// </summary>
        [Test]
        public void ApiVversionAuthorsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string version = null;
            //var response = instance.ApiVversionAuthorsGet(version);
            //Assert.IsInstanceOf<List<Author>> (response, "response is List<Author>");
        }
    }

}
